### ISSUE TITLE
genauen gewichteten Notendurchschnitt berechnen

### ISSUE THREAD

**Issue by mwohlert** [nerdakademie/Grade-Check#1]
Danke an @JanWerder für den Vorschlag

**Comment by mwohlert** [comment]
Implemented

https://github.com/nerdakademie/Grade-Check/commit/53da0a41b3edacd019ef34104c5beebdafbda440

**Comment by mwohlert** [comment]
Implement weighted average

**Comment by mwohlert** [comment]
Now fully implemented by @DZHAGUU 
https://github.com/nerdakademie/Grade-Check/commit/1ccbedbc270a67c6f4ff6c2d0119e0a3ad9a4ccf

**Comment by JanWerder** [comment]
... und gefixed
https://github.com/nerdakademie/Grade-Check/commit/4f97f8e7809484861b9641d7940559d4c6f83306
